# Home page
index:
    path: /
    defaults: { _controller: AppBundle:Default:index }

# Game creation form
create_game_form:
    path: /game/create
    defaults: { _controller: AppBundle:Game:createGameForm }

# Game creation form handling
create_game:
    path: /game/create/{opponent}
    defaults: { _controller: AppBundle:Game:createGame }
    requirements:
        page: '\d+'

# Game display page
show_game:
    path: /game/{gameId}
    defaults: { _controller: AppBundle:Game:showGame }

# Accessed when the player places a card
place_card:
    path: /game/{gameId}/place-card/{cardId}
    defaults: { _controller: AppBundle:Game:placeCard }

# Import FOSUserBundle routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Import EasyAdmin routes
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
